export const  DROPDOWNVALUE="DROPDOWNVALUE"
export const  SET_DROPDOWNVALUE="SET_DROPDOWNVALUE"
export const SELECTEDDROPDVALUE="SELECTEDDROPDVALUE"
export const SET_SELECTEDDROPDVALUE="SET_SELECTEDDROPDVALUE"